// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_upload.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getUploadSession = `-- name: GetUploadSession :one
SELECT uuid, repo, bytes_received, created_at, expires_at FROM upload_sessions
WHERE uuid = ? AND repo = ?
`

func (q *Queries) GetUploadSession(ctx context.Context, uuid uuid.UUID, repo string) (*UploadSession, error) {
	row := q.db.QueryRowContext(ctx, getUploadSession, uuid, repo)
	var i UploadSession
	err := row.Scan(
		&i.Uuid,
		&i.Repo,
		&i.BytesReceived,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}
