// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insert_upload.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUploadSession = `-- name: CreateUploadSession :exec
INSERT INTO upload_sessions (
  uuid, repo, created_at, expires_at
)
VALUES (?, ?, ?, ?)
`

type CreateUploadSessionParams struct {
	Uuid      uuid.UUID `json:"uuid"`
	Repo      string    `json:"repo"`
	CreatedAt uint64    `json:"created_at"`
	ExpiresAt uint64    `json:"expires_at"`
}

func (q *Queries) CreateUploadSession(ctx context.Context, arg CreateUploadSessionParams) error {
	_, err := q.db.ExecContext(ctx, createUploadSession,
		arg.Uuid,
		arg.Repo,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}
