// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
)

type Blob struct {
	Digest    string `json:"digest"`
	Size      uint64 `json:"size"`
	CreatedAt uint64 `json:"created_at"`
}

type IndexManifest struct {
	IndexDigest string `json:"index_digest"`
	ChildDigest string `json:"child_digest"`
	Position    uint64 `json:"position"`
}

type Manifest struct {
	Digest    string `json:"digest"`
	MediaType string `json:"media_type"`
	Size      uint64 `json:"size"`
	CreatedAt uint64 `json:"created_at"`
}

type ManifestBlob struct {
	ManifestDigest string `json:"manifest_digest"`
	BlobDigest     string `json:"blob_digest"`
	Role           string `json:"role"`
	Position       uint64 `json:"position"`
}

type Tag struct {
	Repo           string `json:"repo"`
	TagName        string `json:"tag_name"`
	ManifestDigest string `json:"manifest_digest"`
	UpdatedAt      uint64 `json:"updated_at"`
}

type UploadSession struct {
	Uuid          uuid.UUID `json:"uuid"`
	Repo          string    `json:"repo"`
	BytesReceived uint64    `json:"bytes_received"`
	CreatedAt     uint64    `json:"created_at"`
	ExpiresAt     uint64    `json:"expires_at"`
}
