// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_upload.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const updateUploadSessionBytesReceived = `-- name: UpdateUploadSessionBytesReceived :exec
UPDATE upload_sessions
  SET bytes_received = ?
WHERE uuid = ? AND repo = ?
`

type UpdateUploadSessionBytesReceivedParams struct {
	BytesReceived uint64    `json:"bytes_received"`
	Uuid          uuid.UUID `json:"uuid"`
	Repo          string    `json:"repo"`
}

func (q *Queries) UpdateUploadSessionBytesReceived(ctx context.Context, arg UpdateUploadSessionBytesReceivedParams) error {
	_, err := q.db.ExecContext(ctx, updateUploadSessionBytesReceived, arg.BytesReceived, arg.Uuid, arg.Repo)
	return err
}
